name: Build And Deploy
run-name: Deploy recetas.jaimeelingeniero.es to AWS S3

on:
  workflow_dispatch: # allow manual trigger
  push:
    tags: ["[1-9].[0-9][0-9]?.[0-9][0-9]?"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@6
      - name: Setup node
        uses: actions/setup-node@6
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com/
          scope: "@jaimemartinmartin15"
      - name: Install
        run: npm ci --no-audit --no-fund
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
      - name: Generate icons
        run: npm run icons
      - name: Build
        run: npm run build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@6
        with:
          mask-aws-account-id: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-south-2
      - name: Deploy
        run: |
          aws --version
          aws s3 sync ./dist/recetas/browser \
                      s3://recetas.jaimeelingeniero.es \
                      --delete \
                      --exclude 3rdpartylicenses.txt
          aws s3 cp ./dist/recetas/3rdpartylicenses.txt s3://recetas.jaimeelingeniero.es
